# Generated by Django 3.0.3 on 2020-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='end_time',
            new_name='close_time',
        ),
    ]
