# Generated by Django 3.0.3 on 2020-02-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200228_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status_remark',
            field=models.TextField(null=True),
        ),
    ]
