# Generated by Django 3.0.3 on 2020-02-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200229_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status_remark',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
