# Generated by Django 3.0.3 on 2020-02-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200229_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
