# Generated by Django 3.0.3 on 2020-02-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200229_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('รออนุมัติ', 'Unknow'), ('ไม่อนุมัติ', 'No'), ('อนุมัติ', 'Yes')], default=None, max_length=100, null=True),
        ),
    ]
