# Generated by Django 3.0.3 on 2020-03-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20200306_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('รออนุมัติ', 'Unknow'), ('ไม่อนุมัติ', 'No'), ('อนุมัติ', 'Yes')], default='Unknow', max_length=100, null=True),
        ),
    ]
